# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24b635c3e387b60bd459bba184d8dab82ebc764ed9bd99f4e2c92f7d85221a00c335b0a89fa7551c8984aca5a66e824e596a62a1752044b349d9ce00d5f7a765

test:
  secret_key_base: f46881439105050df36481b4e8d57848a084f84d12cd3e0f320e46ebe4e1370e65b3354d028a960c51076d28e162322f44bd9090f339bc44ad4fda136aa65502

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
